# Generated by Django 4.2.26 on 2025-11-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
